public class Solution{
    
    // MARK: Find the only single number in an array
    // Return the number which is present only once.
    // All numbers belong to the range- 1 to nums.length.
    public int singleNumber(int[] nums){
        int result = 0;

        for(int i = 0; i < nums.length; i++){
            result ^= nums[i];
        }

        return result ^ 0;
    }
    
    // MARK: Find the difference between two strings
    // String t is generated by random shuffling string s and then add one more letter at a random position.
    // Find the letter that was added in t.
    // Example: s: abcde, t: cfdbae should return f
    public char findDifferenceInStrings(String s1, String s2){
        char result = '!';

        for(char c : s1.toCharArray())
            result ^= c;

        for(char c : s2.toCharArray())
            result ^= c;

        return (char) (result ^ '!');
    }
}